apiVersion: networking.k8s.io/v1
kind: Ingress
  meta
name: rag-ingress
namespace: rag
annotations:
  traefik.ingress.kubernetes.io/router.entrypoints: websecure
  traefik.ingress.kubernetes.io/router.tls: "true"
  cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - rag.yourdomain.ru
      secretName: rag-tls
  rules:
    - host: rag.yourdomain.ru
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: rag-backend
                port:
                  number: 8000
