apiVersion: v1
kind: Secret
  meta
name: postgres-credentials
namespace: rag
type: Opaque

  POSTGRES_HOST: <base64 хоста из output Terraform>
  POSTGRES_USER: cmFnX3VzZXI=
  POSTGRES_PASSWORD: <base64 пароля>
  POSTGRES_DB: cmFnX2Ri
