apiVersion: v1
kind: Secret
  meta
name: rag-secrets
namespace: rag
type: Opaque

  GIGACHAT_CLIENT_ID: ${GIGACHAT_CLIENT_ID_B64}
  GIGACHAT_SECRET: ${GIGACHAT_SECRET_B64}
  YC_API_KEY: ${YC_API_KEY_B64}
  JWT_SECRET: ${JWT_SECRET_B64}
